### ISSUE TITLE
Detail: DNS problem: SERVFAIL looking up TXT for

### ISSUE THREAD

**Issue by nixprosoft** [siilike/certbot-dns-standalone#1]
```
root@gsah:/etc/letsencrypt/renewal# certbot certonly -d *.gradstudyabroad.ru -d gradstudyabroad.ru
Saving debug log to /var/log/letsencrypt/letsencrypt.log

How would you like to authenticate with the ACME CA?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Obtain certificates using an integrated DNS server
(certbot-dns-standalone:dns-standalone)
2: Nginx Web Server plugin (nginx)
3: Spin up a temporary webserver (standalone)
4: Place files in webroot directory (webroot)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-4] then [enter] (press 'c' to cancel): 1
Plugins selected: Authenticator certbot-dns-standalone:dns-standalone, Installer None

Please choose an account
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: gradstudyabroad.ru@2018-03-20T19:53:02Z (6bf9)
2: gradstudyabroad.ru@2017-05-09T22:23:46Z (1cbc)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1
Attempting to parse the version 0.34.2 renewal configuration file found at /etc/letsencrypt/renewal/gradstudyabroad.ru-0001.conf with version 0.31.0 of Certbot. This might not work.
Attempting to parse the version 0.36.0 renewal configuration file found at /etc/letsencrypt/renewal/myunibot.com-0001.conf with version 0.31.0 of Certbot. This might not work.
Attempting to parse the version 0.35.0 renewal configuration file found at /etc/letsencrypt/renewal/studyqa.com-0001.conf with version 0.31.0 of Certbot. This might not work.
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for gradstudyabroad.ru
dns-01 challenge for gradstudyabroad.ru
Waiting 0 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. gradstudyabroad.ru (dns-01): urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up TXT for _acme-challenge.gradstudyabroad.ru, gradstudyabroad.ru (dns-01): urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up TXT for _acme-challenge.gradstudyabroad.ru

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: gradstudyabroad.ru
   Type:   None
   Detail: DNS problem: SERVFAIL looking up TXT for
   _acme-challenge.gradstudyabroad.ru

   Domain: gradstudyabroad.ru
   Type:   None
   Detail: DNS problem: SERVFAIL looking up TXT for
   _acme-challenge.gradstudyabroad.ru

```

**Comment by siilike** [comment]
You are missing the NS record for acme.gradstudyabroad.ru, should be ns-acme.gradstudyabroad.ru.

**Comment by nixprosoft** [comment]
> ns-acme.gradstudyabroad.ru

It is exists:
```
#dig +nocmd ns-acme.gradstudyabroad.ru ANY +multiline +noall +answer
ns-acme.gradstudyabroad.ru. 1534 IN A 176.9.46.158
```

**Comment by nixprosoft** [comment]
Maybe 
`ns-acme  IN  AAAA  2a01:4f8:150:62a4::2`
also needed?

**Comment by siilike** [comment]
That is the A record that needs to point to the server that runs certbot. But you also need to create a NS record for acme.gradstudyabroad.ru that points to ns-acme.gradstudyabroad.ru: `acme IN NS ns-acme.gradstudyabroad.ru.`

**Comment by nixprosoft** [comment]
So in subdomain DNS records I have this:
`acme. IN NS ns-acme.gradstudyabroad.ru.`
![2019-08-03_21-12-40](https://user-images.githubusercontent.com/5313478/62415519-8441c180-b633-11e9-8648-3f84cdc6a4dd.png)

**Comment by nixprosoft** [comment]
Wrote a ticket to hosting support. Waiting answer.

**Comment by nixprosoft** [comment]
Tell me please: is there any difference between
1) Creating subdomain acme.domain.com and adding NS record into
or
2) Adding NS record in DNS records of domain.com directly

**Comment by nixprosoft** [comment]
Maybe hosting overrides subdomain NS record with his own:
```
ns1.pa.infobox.ru
ns2.pa.infobox.ru
```

No answer for acme.gradstudyabroad.ru
```
# dig +nocmd gradstudyabroad.ru NS +multiline +noall +answer
gradstudyabroad.ru.     3600 IN NS ns1.pa.infobox.ru.
gradstudyabroad.ru.     3600 IN NS ns2.pa.infobox.ru.
# dig +nocmd acme.gradstudyabroad.ru NS +multiline +noall +answer
#

```

**Comment by siilike** [comment]
Yes, those two are totally different, it needs to be under the acme subdomain. This plugin has an integrated DNS server to reply to the challenge requests, but it does not respond to any others. So, the DNS needs to be configured so that anything under acme.gradstudyabroad.ru gets redirected to certbot, but not the whole domain.

Also note that you cannot run a DNS server on the same IP address as they both need to use port 53.

**Comment by nixprosoft** [comment]
Hosting tech support answered:
`The subdomain inherits the DNS servers of the primary domain; it cannot be delegated to other DNS.`

Certbot runs on different server, there is no DNS service running.

**Comment by nixprosoft** [comment]
@siilike Do you think it's possible to change DNS for subdomain on shared hosting like Infobox?

**Comment by siilike** [comment]
Well, you could try using another domain for certbot then. The domain you are asking the certificate for only needs to have the _acme-challenge CNAME record, the acme ones can be on another one, e.g. you set up acme.xyz.com and acme-ns.xyz.com and then if you want a certificate for gradstudyabroad.ru you only need to create a _acme-challenge.gradstudyabroad.ru CNAME record that points to gradstudyabroad.ru.acme.xyz.com.

If you want free DNS hosting, try CloudFlare. But you probably cannot use the domain you have in Infobox.

**Comment by nixprosoft** [comment]
So, the solution may be:
1) Using DNS in different hosting to create `acme.xyz.com` and `acme-ns.xyz.com`
2) Create another domain, using current hosting, with `acme` and `acme-ns` subdomain records
M?

**Comment by siilike** [comment]
According to what they replied you they don't support creating NS records for subdomains, so you cannot use the current hosting for that. So, the only option is to use another domain that is hosted somewhere else. But as I wrote, you can easily just register a domain and host it on CloudFlare without paying anything monthly.

**Comment by nixprosoft** [comment]
I will try for the first - register another domain in our hosting (there is still a bit paid domains limit left), change NS server of domain and add needed subdomain. If I fail, will try CloudFlare.
Thanks a lot!
