### ISSUE TITLE
Is It me or has something changed?

### ISSUE THREAD

**Issue by pwpreacher** [siilike/certbot-dns-standalone#12]
I have used your plugin before successfully, I just tried to use it again and there was a **Challenge failed for domain chat.knightirc.net**

the command I issued was 

`certbot certonly --preferred-challenges dns --authenticator certbot-dns-standalone:dns-standalone --certbot-dns-standalone:dns-standalone-port=53 -d chat.knightirc.net`

>  The following errors were reported by the server:
> 
>    Domain: chat.knightirc.net
>    Type:   dns
>    Detail: DNS problem: NXDOMAIN looking up TXT for
>    _acme-challenge.chat.knightirc.net - check that a DNS record exists
>    for this domain

port 53 open, and dig shows that acme is configured:

> ;; QUESTION SECTION:
> ;acme.knightirc.net.            IN      A
> 
> ;; AUTHORITY SECTION:
> acme.knightirc.net.     300     IN      NS      ns-acme.knightirc.net.
> 
> ;; ADDITIONAL SECTION:
> ns-acme.knightirc.net.  300     IN      A       69.60.109.114

So have i goofed something up, or have letsencrypt changed something?

shalom

Preacher

**Comment by siilike** [comment]
Does it work without the port argument? This is the only thing that has changed. v1.0.1 did not have it.

Perhaps something else is running on port 53 or it is blocked by firewall.

**Comment by pwpreacher** [comment]
Okay now it is working with or without the port command......

I wonder if they were tinkering at their end on how they look at dns?
