### ISSUE TITLE
Plugin is no longer supported?

### ISSUE THREAD

**Issue by bobcodev** [siilike/certbot-dns-standalone#16]
«1: Obtain certificates using an integrated DNS server (certbot-dns-standalone:dns-standalone)» not available:

```
sudo certbot certonly
Saving debug log to /var/log/letsencrypt/letsencrypt.log

How would you like to authenticate with the ACME CA?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Spin up a temporary webserver (standalone)
2: Place files in webroot directory (webroot)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel):
```

```
sudo certbot --non-interactive --agree-tos --email support@domain.com certonly   --preferred-challenges dns --authenticator certbot-dns-standalone:dns-standalone --certbot-dns-standalone:dns-standalone-address=0.0.0.0 --certbot-dns-standalone:dns-standalone-ipv6-address=:: --certbot-dns-standalone:dns-standalone-port=53 -d *.domain.com
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: --certbot-dns-standalone:dns-standalone-address 0.0.0.0 --certbot-dns-standalone:dns-standalone-ipv6-address :: --certbot-dns-standalone:dns-standalone-port 53
```

Linux services 5.4.0-65-generic

**Comment by doza62** [comment]
it looks like you have not installed the plugin. If I'm not mistaken; i believe the default (standalone) option will not work with wildcards. That is why this plugin will run not only a webserver (like the standalone option) but a DNS server so it can respond to _acme-challenge records. You should install with:

`pip3 install certbot certbot-dns-standalone`

And then you chan check if it is installed by doing `sudo certbot certonly`. There should appear another option like so:

```
How would you like to authenticate with the ACME CA?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Obtain certificates using an integrated DNS server
(certbot-dns-standalone:dns-standalone)
2: Spin up a temporary webserver (standalone)
3: Place files in webroot directory (webroot)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-4] then [enter] (press 'c' to cancel):
```

**Comment by mvduin** [comment]
If anything it's actually _too new_, e.g. it's not packaged for current stable Debian/Ubuntu releases but it is for the next Debian and Ubuntu releases:

Debian 12 "bookworm" (currently in testing): [python3-certbot-dns-standalone](https://packages.debian.org/bookworm/python3-certbot-dns-standalone)
Ubuntu 22.04 "Jammy Jellyfish" (release planned 2022-04-21): [python3-certbot-dns-standalone](python3-certbot-dns-standalone)

On these releases (and of course Debian "sid" (unstable)), you can install it using the package manager:
```
sudo apt install python3-certbot-dns-standalone
```
