### ISSUE TITLE
certbot-dns-standalone on Fedora 36

### ISSUE THREAD

**Issue by johnfawcett** [siilike/certbot-dns-standalone#17]
On Fedora 34 this was working, with just dnf install certbot pip and pip3 install certbot-dns-standalone. On Fedora 36 after the install the authenticator does not show up as those listed by certbot certonly. In non interactive mode an error is given.

<pre>certbot --non-interactive --agree-tos --email certmaster@example.com certonly   --preferred-challenges dns --authenticator certbot-dns-standalone:dns-standalone   --certbot-dns-standalone:dns-standalone-address=0.0.0.0   --certbot-dns-standalone:dns-standalone-ipv6-address=::   --certbot-dns-standalone:dns-standalone-port=53   -d example.com
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --certbot-dns-standalone:dns-standalone-address=0.0.0.0 --certbot-dns-standalone:dns-standalone-ipv6-address=:: --certbot-dns-standalone:dns-standalone-port=53
</pre>

Running again without the option parameters gives:

<pre>
certbot --non-interactive --agree-tos --email certmaster@example.com certonly   --preferred-challenges dns --authenticator certbot-dns-standalone:dns-standalone    -d example.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The requested certbot-dns-standalone:dns-standalone plugin does not appear to be installed
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
</pre>

The log shows

<pre>
2022-10-19 11:07:58,825:DEBUG:certbot._internal.plugins.selection:Requested authenticator certbot-dns-standalone:dns-standalone and installer None
2022-10-19 11:07:58,825:DEBUG:certbot._internal.plugins.selection:No candidate plugin
2022-10-19 11:07:58,825:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/main.py", line 1744, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/main.py", line 1572, in certonly
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/usr/lib/python3.10/site-packages/certbot/_internal/plugins/selection.py", line 257, in choose_configurator_plugins
    diagnose_configurator_problem("authenticator", req_auth, plugins)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/plugins/selection.py", line 377, in diagnose_configurator_problem
    raise errors.PluginSelectionError(msg)
certbot.errors.PluginSelectionError: The requested certbot-dns-standalone:dns-standalone plugin does not appear to be installed
2022-10-19 11:07:58,826:ERROR:certbot._internal.log:The requested certbot-dns-standalone:dns-standalone plugin does not appear to be installed
</pre>

**Comment by siilike** [comment]
Try removing the `certbot-dns-standalone:` prefixes which are obsolete in newer certbot versions.

**Comment by johnfawcett** [comment]
Still get errors on the optional parameters:

<pre>
certbot: error: unrecognized arguments: --dns-standalone-address=0.0.0.0 --dns-standalone-ipv6-address=:: --dns-standalone-port=53
</pre>

and removing those still gives an error that plugin is not installed

<pre>
certbot --non-interactive --agree-tos --email certmaster@example.com certonly   --preferred-challenges dns --authenticator dns-standalone    -d example.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The requested dns-standalone plugin does not appear to be installed
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
</pre>

Presumably it's some incompatibility between the certbot installed via dnf and the one available from pip.

Fedora 36 rpm has certbot 1.30.0
pip has certbot 1.31.0 and certbot-dns-standalone 1.0.3

I have worked around it by doing this, which may be helpful for others with the same issue:

<pre>
python3 -m venv /opt/certbot/
/opt/certbot/bin/pip install --upgrade pip
/opt/certbot/bin/pip install certbot
/opt/certbot/bin/pip install certbot-dns-standalone
</pre>

and then running certbot as:
<pre>
/opt/certbot/bin/certbot
</pre>

instead of just certbot which picks up the Fedora 36 installed one. I guess only solution for working out of the box again will be for Fedora to package certbot 1.31.0

I'll file a request.

**Comment by siilike** [comment]
The solution would likely have been to uninstall the certbot package and install both certbot and the plugin from pip.
