### ISSUE TITLE
Snap support

### ISSUE THREAD

**Issue by ncovercash** [siilike/certbot-dns-standalone#19]
Would it be possible for this plugin to be released on snap?  It seems the current certbot instructions prefer installing via snap, however, with this configuration it is not possible for certbot to find this plugin (or any other pip-installed plugin, for that matter).

There are some instructions here: https://eff-certbot.readthedocs.io/en/stable/contributing.html#writing-your-own-plugin-snap

**Comment by siilike** [comment]
Support added.
