### ISSUE TITLE
Confusing usage documentation 

### ISSUE THREAD

**Issue by andros-ua** [siilike/certbot-dns-standalone#22]
Document begins from statement that we have example.com domain for certbot service and example.net for certificate target domain.
Than we have this command:
```
certbot --non-interactive --agree-tos --email certmaster@example.com certonly \ --preferred-challenges dns --authenticator dns-standalone \ --dns-standalone-address=1.2.3.4 \ -d example.com -d '*.example.com'
```
Shouldn't we have to use example.net instead?

**Comment by siilike** [comment]
Indeed, I have changed it to say `example.net` instead.
