### ISSUE TITLE
certbot renew: Works for wildcard cert alone but not if called in crontab

### ISSUE THREAD

**Issue by md-admin** [siilike/certbot-dns-standalone#23]
Today I realized a fault during renewal of a bunch of certs. The error only occurs for our wildcard certificate when something like:

   **certbot renew  -v --dry-run  --config /etc/letsencrypt/cli.ini**

is run or from /etc/crontab:

   **certbot renew**.

If I use: 

   **certbot certonly  -v --dry-run  --config /etc/letsencrypt/cli.ini  --preferred-challenges dns-01  --authenticator dns-standalone --dns-standalone-port=53 --dns-standalone-address=#.#.#.# --domain "domain.tld,*.domain.tld"**

from the commandline everything is carried out without any error (even without --dry-run). 

To my dismay I'm completely unaware of Python and would like to ask for help in that matter. Googling around or searching here for issues could not help me so far. Please find attached some sompiled information and thank you in advance for any hint.

[domain.tld.conf.zip](https://github.com/siilike/certbot-dns-standalone/files/12239401/domain.tld.conf.zip)
[renewFAULT.zip](https://github.com/siilike/certbot-dns-standalone/files/12239387/renewFAULT.zip)
[renewSUCCESS.zip](https://github.com/siilike/certbot-dns-standalone/files/12239389/renewSUCCESS.zip)

**Comment by md-admin** [comment]
Please excuse, I forgot to mention that 

a) we are running on openSUSE Tumbleweed (with all updates) and b) use 

```
S  | Name                         | Type    | Version      | Arch   | Repository
---+------------------------------+---------+--------------+--------+-----------
i+ | python311-certbot            | package | 2.6.0-1.2    | noarch | twI.oss
i  | python311                    | package | 3.11.4-1.1   | x86_64 | twI.oss
i  | python311-pip                | package | 23.1.2-2.2   | noarch | twI.oss

```
with c) dns-standalone installed via pip 

```
Package                Version
---------------------- --------
acme                   2.6.0
apipkg                 3.0.1
certbot                2.6.0
certbot-dns-standalone 1.1
dnslib                 0.9.23
pip                    23.1.2

```

**Comment by siilike** [comment]
The error is "Failed to renew certificate messe-duesseldorf.de with error: None of the preferred challenges are supported by the selected plugin".

This could happen e.g. when you do something like `certbot certonly --preferred-challenges dns-01 --authenticator nginx` as the `nginx` authenticator cannot handle DNS.

The configuration file looks OK, though. You could try creating a new configuration and removing the old one if it works.

**Comment by md-admin** [comment]
> This could happen e.g. when you do something like `certbot certonly --preferred-challenges dns-01 --authenticator nginx` as the `nginx` authenticator cannot handle DNS.

But the authenticator is **dns-standalone**, neither apache nor nginx? What made you think I used nginx?


> The configuration file looks OK, though. You could try creating a new configuration and removing the old one if it works.

To be honest this was the second occurence of that error. The last time I already removed the config from renewal subdirectory and had certbot recreate it. What else can you recommend and could you find any hint in the letsencrypt.logs? These lines seem to indicate some issues but I can not interpret them:

```
2023-08-02 12:44:34,729:DEBUG:certbot._internal.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/certbot/_internal/renewal.py", line 533, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python3.11/site-packages/certbot/_internal/main.py", line 1547, in renew_cert
    renewed_lineage = _get_and_save_cert(le_client, config, lineage=lineage)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/certbot/_internal/main.py", line 129, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python3.11/site-packages/certbot/_internal/renewal.py", line 395, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/certbot/_internal/auth_handler.py", line 80, in handle_authorizations
    achalls = self._choose_challenges(authzrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/certbot/_internal/auth_handler.py", line 238, in _choose_challenges
    self._get_chall_pref(authzr.body.identifier.value))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/certbot/_internal/auth_handler.py", line 260, in _get_chall_pref
    raise errors.AuthorizationError(
certbot.errors.AuthorizationError: None of the preferred challenges are supported by the selected plugin

```

**Comment by siilike** [comment]
> > This could happen e.g. when you do something like `certbot certonly --preferred-challenges dns-01 --authenticator nginx` as the `nginx` authenticator cannot handle DNS.
> 
> But the authenticator is **dns-standalone**, neither apache nor nginx? What made you think I used nginx?

I am not saying you did, just that *if* you did, you would get the same error.

> > The configuration file looks OK, though. You could try creating a new configuration and removing the old one if it works.

If you remove the `pref_challs` option from the configuration it should not trigger this error.

I don't think you actually need to set the `--preferred-challenges` option when setting the authenticator as the plugin only supports DNS anyway.

**Comment by md-admin** [comment]
Thank you for your patience. I removed the `pref_challs = dns-01,` option from the renewal configuration but the error still appears (together with Traceback):

The following simulated renewals failed:
  /etc/letsencrypt/live/messe-duesseldorf.de/fullchain.pem (failure)

**Comment by siilike** [comment]
Please also post the new log.

The relevant code from certbot is this:
```
    def _get_chall_pref(self, domain: str) -> List[Type[challenges.Challenge]]:
        """Return list of challenge preferences.

        :param str domain: domain for which you are requesting preferences

        """
        chall_prefs = []
        # Make sure to make a copy...
        plugin_pref = self.auth.get_chall_pref(domain)
        if self.pref_challs:
            plugin_pref_types = {chall.typ for chall in plugin_pref}
            for typ in self.pref_challs:
                if typ in plugin_pref_types:
                    chall_prefs.append(challenges.Challenge.TYPES[typ])
            if chall_prefs:
                return chall_prefs
            raise errors.AuthorizationError(
                "None of the preferred challenges "
                "are supported by the selected plugin")
        chall_prefs.extend(plugin_pref)
        return chall_prefs
```
That `if self.pref_challs` corresponds to the `pref_challs` in the config file, so if it is not set, the error shouldn't be raised at all.

**Comment by md-admin** [comment]
Is the observation correct that the difference is between the verbs `certonly` and `renew`? And what about certbot's version: Is it compatible for the plugin?

[le.log.zip](https://github.com/siilike/certbot-dns-standalone/files/12241914/le.log.zip)

**Comment by siilike** [comment]
`certonly` creates a new configuration and fetches the certificate, `renew` uses that created configuration to renew the certificate.

You could try running certbot with the `--config-dir` argument to use a fresh directory for everything instead of `/etc/letsencrypt/`.

You are running the latest version of certbot and the plugin works fine with it.

If it still doesn't work I suggest you open a bug report for certbot itself.

**Comment by md-admin** [comment]
Just created an issue at [https://github.com/certbot/certbot/issues/9742](url).

**Comment by md-admin** [comment]
From `alexzorin` at [https://github.com/certbot/certbot/issues/9742](url):

> It looks like you are probably setting `preferred-challenges = http-01` in `/etc/letsencrypt/cli.ini`. This has the highest possible precedence (other than setting `--preferred-challenges` on the CLI, which is exactly why `certonly` worked for you) and will affect all certificates.

Thank you for giving this hint. I removed that setting and tried `certbot renew  -v --dry-run` with a positive result:

```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/domain.tld.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not due for renewal, but simulating renewal for dry run
Plugins selected: Authenticator dns-standalone, Installer None
Simulating renewal of an existing certificate for domain.tld and *.domain.tld
Performing the following challenges:
dns-01 challenge for domain.tld
dns-01 challenge for domain.tld
Waiting 0 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges
Dry run: skipping deploy hook command: /etc/letsencrypt/renewal-hooks/deploy/notifyByMail

```
