### ISSUE TITLE
Is it possible to define whitelist domains

### ISSUE THREAD

**Issue by saudiqbal** [siilike/certbot-dns-standalone#3]
Looks like anyone can add my domain and get their own wildcard certificate just by pointing their domains to my DNS server like

_acme-challenge  IN  CNAME  evildomain.net.acme.mydomain.com.

**Comment by siilike** [comment]
When someone points their _acme-challenge to your domain YOU can get certificates for THEIR domains. They will not be able to do that, because they cannot set the challenge response as they don't control acme.mydomain.com.
