### ISSUE TITLE
How to do manual uninstallation?

### ISSUE THREAD

**Issue by harmin-parra** [siilike/certbot-dns-standalone#5]
After installing the plugin from the master branch with commands
```
setup.py build
setup.py install
```

How can I uninstall it afterwards ?

**Comment by siilike** [comment]
`setup.py` will tell you the directory where it gets installed. Run it again and you will see, for me it is `/usr/local/lib/python3.7/dist-packages/certbot_dns_standalone/`. Then just remove the directory.
