### ISSUE TITLE
Docker instructions?

### ISSUE THREAD

**Issue by Germs2004** [siilike/certbot-dns-standalone#7]
Can you please give instructions on how to set this up with Docker?  I'm still learning Docker but it seems like maybe this isn't Docker-ready?

I ran this:
`docker build -t siilike\certbot-dns-standalone:latest github.com/siilike/certbot-dns-standalone`
But it gave me an image that doesn't seem to expose port 53.

If this plugin is still supported, it would be great if you had a fully documented image on DockerHub for us to use.

Thank you!

**Comment by siilike** [comment]
I am not that familiar with Docker either, so there currently is no explicit support for it. You might want to check out the Dockerfiles of other certbot plugins and make one based on those.

**Comment by Germs2004** [comment]
I think your plugin sounds really great so I hope somebody will come along with Docker skills and get it to work in Docker.  Or possibly one of those [other](https://github.com/linuxserver/docker-letsencrypt) certbot Docker [maintainers](https://github.com/certbot-docker/certbot-docker) can integrate your plugin into their Docker images.

A similar project is [acme-dns](https://github.com/joohoi/acme-dns).  Acme-dns runs as a separate docker container and may be a bit more useful in some situations since it can work with more than just certbot, but for people who just need certbot, I think your plugin sounds much easier to use.

**Comment by siilike** [comment]
Well, you don't have to put every little thing into a container. All you need to do is install Python 3 and PIP if not yet installed and install certbot from pip. It takes a lot more time to configure the DNS records than it takes to install the software.

**Comment by 93million** [comment]
Hi @Germs2004 @siilike. I created a project called [CertCache](/93million/certcache) that brings Docker support to certbot-dns-standalone (and other Certbot DNS plugins)

I created a screencast that walks through the process of setting up a secure Nginx web server in Docker and getting a wildcard Let's Encrypt certificate

https://www.youtube.com/watch?v=J7ckr1Mzw_8
