### ISSUE TITLE
SERVFAIL when looking up CAA records

### ISSUE THREAD

**Issue by sverrevh** [siilike/certbot-dns-standalone#9]
When using the dns-standalone module for a full domain instead of a subdomain, it will also have to serve a CAA record or at least not return SERVFAIL or NOTIMP in order for Letsencrypt to be able to issue a certificate:
https://letsencrypt.org/docs/caa/
My domain does not have DNSSEC configured.

From the Letsencrypt logging: (replaced my domain with domain.com)
```
2020-04-28 09:00:00,114:DEBUG:acme.client:Received response:
HTTP 403
Server: nginx
Date: Tue, 28 Apr 2020 07:00:00 GMT
Content-Type: application/problem+json
Content-Length: 879
Connection: keep-alive
Boulder-Requester: 84247612
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce:

{
  "type": "urn:ietf:params:acme:error:caa",
  "detail": "Error finalizing order :: Rechecking CAA for \"domain.com\" and 1 more identifiers failed. Refer to sub-problems for more information",
  "status": 403,
  "subproblems": [
    {
      "type": "urn:ietf:params:acme:error:caa",
      "detail": "Error finalizing order :: While processing CAA for domain.com: DNS problem: SERVFAIL looking up CAA for domain.com - the domain's nameservers may be malfunctioning",
      "status": 403,
      "identifier": {
        "type": "dns",
        "value": "domain.com"
      }
    },
    {
      "type": "urn:ietf:params:acme:error:caa",
      "detail": "Error finalizing order :: While processing CAA for *.domain.com: DNS problem: query timed out looking up CAA for domain.com",
      "status": 403,
      "identifier": {
        "type": "dns",
        "value": "*.domain.com"
      }
    }
  ]
}
```

**Comment by siilike** [comment]
Can you explain why are you using it like this? You shouldn't use it in place of a full DNS server, but only for serving the _acme-challenge records. It will reply with the current token(s) regardless of the actual request.

**Comment by sverrevh** [comment]
I'm using a service that creates on the fly subdomains for *.domain.com, so my server is the webserver and nameserver at the same time. I pointed the NS records of the domain to the server. I kill the service temporarily to swap in your solution to renew the wildcard certificate. Everything goes fine, until Letsencrypt wants to check the CAA record, which is not served and returns either SERVFAIL or NOTIMP instead of NOERROR.
Is there an easy way to add support for a CAA record for domain.com?

**Comment by siilike** [comment]
This cannot really work properly, because while the DNS server is replaced by certbot all other queries will fail which will lead to people being unable to access your site.

So, the solution is to get another IP and run certbot there.

Alternatively, it could be possible to configure the DNS server to proxy the relevant requests to certbot.
